services:
  mongodb:
    image: mongo:latest
    container_name: mihi-shop
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
